import { defineConfig, devices } from '@playwright/test'

// Set by .claude/hooks/session-start.sh only when Claude Code on the web has a
// pre-installed chromium that is not the revision @playwright/test expects,
// and the sandbox blocks cdn.playwright.dev so the matching build cannot be
// downloaded. Unset on local machines and in CI, where Playwright's own
// managed browser is used as usual.
const chromiumExecutable = process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE

export default defineConfig({
  testDir: './e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  reporter: 'html',
  // One canonical set of screenshot baselines (OQ-40), generated by CI's
  // renderer. Playwright's default template appends {projectName} and the
  // platform, which would let a run on another OS quietly mint a second,
  // parallel baseline set and pass against it; with those dropped, such a run
  // compares against CI's images and fails loudly instead.
  snapshotPathTemplate: 'e2e/__screenshots__/{arg}{ext}',
  expect: {
    toHaveScreenshot: {
      // Both numbers were measured rather than guessed (see the PR that added
      // this). Repeated runs against a baseline from the same renderer differ
      // by 0 pixels, so the tolerance only has to cover rounding jitter, not
      // a rasteriser change -- a chromium build bump moves far more than any
      // survivable tolerance and means regenerating the baselines anyway.
      //
      // threshold is per-pixel colour distance. Playwright's 0.2 default is
      // very blind to colour: shifting --accent from #aa3bff to #6b3bff, an
      // obviously different purple, was still reported as zero differing
      // pixels. 0.05 catches #8b3bff (and everything coarser) while still
      // reporting 0 differing pixels run-to-run on an unchanged app.
      threshold: 0.05,
      // How many pixels may differ at all: 0.05% of the image, i.e. 460 px at
      // 1280x720 and 164 px at 390x844. Measured at these settings, the
      // smallest deliberate break tried -- bumping one 12px tab label to 13px
      // -- moved 773-980 px, and adding 1px to the header's padding moved
      // 3424-19905 px, so both fail on every shot with room to spare.
      maxDiffPixelRatio: 0.0005,
    },
  },
  use: {
    baseURL: 'http://localhost:5183',
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        ...(chromiumExecutable
          ? { launchOptions: { executablePath: chromiumExecutable } }
          : {}),
      },
    },
  ],
  webServer: {
    command: 'npm run dev -- --port 5183 --strictPort',
    url: 'http://localhost:5183',
    reuseExistingServer: !process.env.CI,
  },
})
