import { expect, test } from '@playwright/test'

/*
 * Appearance guard (OQ-40). Every other spec in here asserts what the app
 * *does*; these assert what it *looks like*, so a CSS or layout break can't
 * pass CI silently.
 *
 * Baselines live in e2e/__screenshots__/ and are generated by
 * .github/workflows/update-screenshots.yml on a CI runner -- not locally --
 * so the images are always made by the renderer that compares against them.
 * How much that matters here was measured rather than assumed: the chromium a
 * Claude Code web session has pre-installed (141) and the one CI downloads
 * (153) render these six screens within 48 pixels of each other at zero
 * tolerance -- all of it sub-threshold antialiasing on one word of the
 * category tab bar -- so CI's baselines do in fact pass in a web session.
 * That is a courtesy, not a guarantee: another OS's font stack would not be
 * nearly so close, and playwright.config.js deliberately drops the platform
 * suffix from the baseline path so that a machine which renders differently
 * fails loudly instead of minting its own parallel set.
 *
 * Deliberately few shots: this file rides the same required status check as
 * the rest of the e2e suite, so a flaky baseline blocks every PR in the repo,
 * not just a UI one. Three screens x two viewports, each captured in a state
 * that needs no timing, no network and no interaction beyond a tab click.
 */

// Mobile is 390x844 (the iPhone 12/13/14 CSS viewport): narrow enough to
// cross index.css's 1024px breakpoint, where the root font drops to 16px and
// #root stops being a 480px column and fills the screen -- i.e. the layout
// OQ-9 is actually about.
const VIEWPORTS = [
  { name: 'desktop', viewport: { width: 1280, height: 720 } },
  { name: 'mobile', viewport: { width: 390, height: 844 } },
]

// Puts the page in a state a screenshot can be taken of twice and get the
// same pixels: a tab click leaves the pointer sitting on the button it hit
// (several controls have :hover rules) and leaves that button focused.
const settle = async (page) => {
  await page.mouse.move(0, 0)
  await page.evaluate(async () => {
    if (document.activeElement instanceof HTMLElement) document.activeElement.blur()
    window.scrollTo(0, 0)
    await document.fonts.ready
  })
}

for (const { name, viewport } of VIEWPORTS) {
  test.describe(`${name} appearance`, () => {
    // colorScheme is pinned rather than left to the runner: index.css has a
    // full dark palette behind prefers-color-scheme, so an agent or runner
    // with a dark OS preference would otherwise render a different app.
    test.use({ viewport, colorScheme: 'light', deviceScaleFactor: 1 })

    test.beforeEach(async ({ page }) => {
      // The only seeding these need. Enhance is gated behind the Workshop
      // Enhancements Lab (OQ-32); without this the Enhance tab shows the
      // lock screen rather than the screen being guarded. Everything else is
      // left at its first-run default, which is both the most representative
      // state and the one with the fewest moving parts.
      await page.addInitScript(() => {
        window.localStorage.setItem('enhancementLabLevel', JSON.stringify(1))
      })
      await page.goto('/')
    })

    test('Upgrade screen', async ({ page }) => {
      await expect(page.getByLabel('Damage', { exact: true })).toBeVisible()

      await settle(page)
      await expect(page).toHaveScreenshot(`upgrade-${name}.png`)
    })

    test('Path screen', async ({ page }) => {
      await page.getByRole('tab', { name: 'Path', exact: true }).click()
      await expect(page.getByRole('list', { name: 'Recommended buy order' })).toBeVisible()

      await settle(page)
      // Viewport-sized, not fullPage: the buy-order list is ~4800px tall, and
      // a baseline that size is both slow to compare and churns on any
      // ranking change far below the fold. The first screenful covers the
      // header, the row layout, the per-tree accent borders and the Buy
      // buttons -- the parts a CSS change actually breaks.
      await expect(page).toHaveScreenshot(`path-${name}.png`)
    })

    test('Enhance screen', async ({ page }) => {
      await page.getByRole('tab', { name: 'Enhance', exact: true }).click()
      await expect(page.getByText('1.00×').first()).toBeVisible()

      await settle(page)
      await expect(page).toHaveScreenshot(`enhance-${name}.png`)
    })
  })
}

// Dark palette (OQ-44). index.css declares the dark values twice -- once
// under `prefers-color-scheme: dark`, once under `:root[data-theme='dark']`,
// because a selector list can't span in and out of a @media block -- with
// only a comment asking that they stay in sync. The realistic failure is
// those two blocks drifting apart, which src/index.css.test.js catches by
// comparing their declared custom properties directly: an informative
// "--accent differs" beats a pixel-diff count for that failure, and it's a
// unit test, so it costs nothing here. What that unit test *can't* catch is
// a real browser failing to apply either selector at all (a typo breaking
// `:not(...)`, say) -- so one screenshot stands in for the six a full
// second matrix would cost, chosen for the screen with the most var(--...)
// usage (tree/success/danger accents on top of text/bg/border), at one
// viewport: dark and light differ only in color values, not layout, so the
// mobile-breakpoint crossing the light matrix exists for buys nothing here.
test.describe('dark palette appearance', () => {
  test.use({
    viewport: { width: 1280, height: 720 },
    colorScheme: 'dark',
    deviceScaleFactor: 1,
  })

  test.beforeEach(async ({ page }) => {
    await page.addInitScript(() => {
      window.localStorage.setItem('enhancementLabLevel', JSON.stringify(1))
    })
    await page.goto('/')
  })

  test('Path screen', async ({ page }) => {
    await page.getByRole('tab', { name: 'Path', exact: true }).click()
    await expect(page.getByRole('list', { name: 'Recommended buy order' })).toBeVisible()

    await settle(page)
    await expect(page).toHaveScreenshot('path-desktop-dark.png')
  })
})

// The data-theme override (HeaderMenu's Light/Dark toggle, see App.jsx)
// forces a theme regardless of OS preference. header-menu.spec.js and
// App.test.jsx both check that choosing it sets the `data-theme` attribute;
// neither checks that index.css's selectors actually pick it up. Checked via
// a computed custom property rather than a screenshot -- cheap, runs in a
// real browser's cascade (unlike a jsdom unit test), and a broken selector
// fails naming the exact property and value rather than a pixel count. The
// assertion is self-referential (forcing a theme must reproduce what that
// theme's OS preference alone renders) rather than a hard-coded hex, so it
// doesn't duplicate the palette values index.css.test.js already guards.
test.describe('data-theme override', () => {
  const backgroundOf = (page) =>
    page.evaluate(() =>
      getComputedStyle(document.documentElement).getPropertyValue('--bg').trim(),
    )

  test('data-theme="dark" reproduces the OS-dark background under an OS-light preference', async ({
    page,
  }) => {
    await page.emulateMedia({ colorScheme: 'dark' })
    await page.goto('/')
    const osDarkBg = await backgroundOf(page)

    await page.emulateMedia({ colorScheme: 'light' })
    await page.addInitScript(() =>
      window.localStorage.setItem('themePreference', JSON.stringify('dark')),
    )
    await page.goto('/')
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
    expect(await backgroundOf(page)).toBe(osDarkBg)
  })

  test('data-theme="light" suppresses the OS-dark background', async ({ page }) => {
    await page.emulateMedia({ colorScheme: 'light' })
    await page.goto('/')
    const osLightBg = await backgroundOf(page)

    await page.emulateMedia({ colorScheme: 'dark' })
    await page.addInitScript(() =>
      window.localStorage.setItem('themePreference', JSON.stringify('light')),
    )
    await page.goto('/')
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
    expect(await backgroundOf(page)).toBe(osLightBg)
  })
})
